const baseUrl = import.meta.env.BASE_URL

export const productCategories = [
  { id: 'all', label: 'All categories' },
  { id: 'card-games', label: 'Card Games' },
  { id: 'pokemon-tcg', label: 'Pokemon TCG' },
  { id: 'magic-the-gathering', label: 'Magic: The Gathering' },
  { id: 'yu-gi-oh', label: 'Yu-Gi-Oh!' },
  { id: 'video-games', label: 'Video Games' },
  { id: 'figures', label: 'Figures' },
  { id: 'funko-pops', label: 'Funko Pops' },
  { id: 'sneakers', label: 'Sneakers' },
]

export const inventoryProducts = [
  {
    id: 'pokemon-charizard-ex',
    name: 'Charizard ex - Obsidian Flames',
    categoryId: 'pokemon-tcg',
    categoryName: 'Pokemon TCG',
    departmentId: 'card-games',
    departmentName: 'Card Games',
    condition: 'Near Mint',
    description: 'Modern Pokemon single with dragon artwork and strong binder appeal.',
    featureRank: 1,
    image: `${baseUrl}Images/1.png`,
    price: 34.99,
    tags: ['pokemon', 'charizard', 'dragon', 'single card', 'foil'],
  },
  {
    id: 'yugioh-blue-eyes',
    name: 'Blue-Eyes White Dragon - 25th Anniversary',
    categoryId: 'yu-gi-oh',
    categoryName: 'Yu-Gi-Oh!',
    departmentId: 'card-games',
    departmentName: 'Card Games',
    condition: 'Lightly Played',
    description: 'Classic dragon card for Yu-Gi-Oh collectors.',
    featureRank: 2,
    image: `${baseUrl}Images/2.png`,
    price: 42,
    tags: ['yu-gi-oh', 'blue-eyes', 'dragon', 'anniversary', 'single card'],
  },
  {
    id: 'mtg-ancient-copper-dragon',
    name: 'Ancient Copper Dragon',
    categoryId: 'magic-the-gathering',
    categoryName: 'Magic: The Gathering',
    departmentId: 'card-games',
    departmentName: 'Card Games',
    condition: 'Near Mint',
    description: 'Commander staple from a high-demand Magic set.',
    featureRank: 3,
    image: `${baseUrl}Images/3.png`,
    price: 68.5,
    tags: ['magic', 'mtg', 'dragon', 'commander', 'single card'],
  },
  {
    id: 'pokemon-pikachu-promo',
    name: 'Pikachu Scarlet & Violet Promo',
    categoryId: 'pokemon-tcg',
    categoryName: 'Pokemon TCG',
    departmentId: 'card-games',
    departmentName: 'Card Games',
    condition: 'Near Mint',
    description: 'Display-ready Pokemon promo for casual collectors.',
    featureRank: 4,
    image: `${baseUrl}Images/4.png`,
    price: 12.75,
    tags: ['pokemon', 'pikachu', 'promo', 'single card'],
  },
  {
    id: 'mtg-sleeve-bundle',
    name: 'Dragon Shield Matte Sleeve Bundle',
    categoryId: 'magic-the-gathering',
    categoryName: 'Magic: The Gathering',
    departmentId: 'card-games',
    departmentName: 'Card Games',
    condition: 'New',
    description: 'Tournament-ready sleeves for Magic decks and card storage.',
    featureRank: 5,
    image: `${baseUrl}Images/5.png`,
    price: 14.99,
    tags: ['magic', 'mtg', 'dragon shield', 'sleeves', 'accessory'],
  },
  {
    id: 'switch-pokemon-violet',
    name: 'Pokemon Violet - Nintendo Switch',
    categoryId: 'video-games',
    categoryName: 'Video Games',
    departmentId: 'video-games',
    departmentName: 'Video Games',
    condition: 'Complete in Box',
    description: 'Modern Nintendo Switch title with case and cartridge.',
    featureRank: 6,
    image: `${baseUrl}Images/6.png`,
    price: 39.99,
    tags: ['pokemon', 'switch', 'nintendo', 'video game'],
  },
  {
    id: 'retro-gameboy-color',
    name: 'Game Boy Color - Atomic Purple',
    categoryId: 'video-games',
    categoryName: 'Video Games',
    departmentId: 'video-games',
    departmentName: 'Video Games',
    condition: 'Tested',
    description: 'Retro handheld console with the transparent shell collectors like.',
    featureRank: 7,
    image: `${baseUrl}Images/7.png`,
    price: 89.99,
    tags: ['retro', 'game boy', 'nintendo', 'handheld', 'video game'],
  },
  {
    id: 'funko-luffy-gear-five',
    name: 'Monkey D. Luffy Gear Five Funko Pop',
    categoryId: 'funko-pops',
    categoryName: 'Funko Pops',
    departmentId: 'figures',
    departmentName: 'Figures',
    condition: 'Boxed',
    description: 'Anime collectible figure with display box.',
    featureRank: 8,
    image: `${baseUrl}Images/8.png`,
    price: 24.99,
    tags: ['funko', 'one piece', 'anime', 'figure', 'luffy'],
  },
  {
    id: 'figure-naruto-sage',
    name: 'Naruto Sage Mode Display Figure',
    categoryId: 'figures',
    categoryName: 'Figures',
    departmentId: 'figures',
    departmentName: 'Figures',
    condition: 'New',
    description: 'Shelf-ready anime figure for Naruto collectors.',
    featureRank: 9,
    image: `${baseUrl}Images/9.png`,
    price: 31.5,
    tags: ['naruto', 'anime', 'figure', 'display'],
  },
  {
    id: 'sneaker-jordan-retro',
    name: 'Jordan Retro 4 Collectors Pair',
    categoryId: 'sneakers',
    categoryName: 'Sneakers',
    departmentId: 'sneakers',
    departmentName: 'Sneakers',
    condition: 'Pre-owned',
    description: 'Streetwear staple pair for sneaker collectors.',
    featureRank: 10,
    image: `${baseUrl}Images/10.png`,
    price: 165,
    tags: ['jordan', 'retro', 'sneakers', 'streetwear'],
  },
  {
    id: 'yugioh-dark-magician-girl',
    name: 'Dark Magician Girl - Ultra Rare',
    categoryId: 'yu-gi-oh',
    categoryName: 'Yu-Gi-Oh!',
    departmentId: 'card-games',
    departmentName: 'Card Games',
    condition: 'Near Mint',
    description: 'Fan-favorite Yu-Gi-Oh single in collectible condition.',
    featureRank: 11,
    image: `${baseUrl}Images/11.png`,
    price: 27.25,
    tags: ['yu-gi-oh', 'dark magician girl', 'ultra rare', 'single card'],
  },
  {
    id: 'mtg-collector-booster',
    name: 'MTG Collector Booster Pack',
    categoryId: 'magic-the-gathering',
    categoryName: 'Magic: The Gathering',
    departmentId: 'card-games',
    departmentName: 'Card Games',
    condition: 'Sealed',
    description: 'Sealed Magic pack for collectors chasing premium variants.',
    featureRank: 12,
    image: `${baseUrl}Images/12.png`,
    price: 22.99,
    tags: ['magic', 'mtg', 'sealed', 'booster', 'collector'],
  },
]
